export const data = {
  cardData: [
    { id: 1, img: " ", title: "A", desc: "desc1" },
    { id: 2, img: " ", title: "B", desc: "desc2" },
    { id: 3, img: " ", title: "C", desc: "desc3" },
    { id: 4, img: " ", title: "D", desc: "desc4" },
    { id: 5, img: " ", title: "E", desc: "desc5" },
    { id: 6, img: " ", title: "F", desc: "desc6" },
    { id: 7, img: " ", title: "G", desc: "desc7" },
    { id: 8, img: " ", title: "H", desc: "desc8" },
    { id: 9, img: " ", title: "I", desc: "desc9" },
    { id: 10, img: " ", title: "J", desc: "desc10" },
    { id: 11, img: " ", title: "k", desc: "desc11" },
    { id: 12, img: " ", title: "L", desc: "desc12" },
    { id: 13, img: " ", title: "M", desc: "desc13" },
    { id: 14, img: " ", title: "N", desc: "desc14" },
    { id: 15, img: " ", title: "O", desc: "desc15" },
    { id: 16, img: " ", title: "P", desc: "desc15" },
    { id: 17, img: " ", title: "Q", desc: "desc15" },
    { id: 18, img: " ", title: "R", desc: "desc15" },
    { id: 19, img: " ", title: "S", desc: "desc15" },
    { id: 20, img: " ", title: "T", desc: "desc15" },
    { id: 21, img: " ", title: "U", desc: "desc15" },
    { id: 22, img: " ", title: "V", desc: "desc15" },
    { id: 23, img: " ", title: "W", desc: "desc15" },
    { id: 24, img: " ", title: "X", desc: "desc15" },
    { id: 25, img: " ", title: "Y", desc: "desc15" },
    { id: 26, img: " ", title: "Z", desc: "desc15" },
    { id: 27, img: " ", title: "AAA", desc: "desc15" },
    { id: 28, img: " ", title: "BBB", desc: "desc15" },
    { id: 29, img: " ", title: "CCC", desc: "desc15" },
    { id: 30, img: " ", title: "DDD", desc: "desc15" },
    { id: 31, img: " ", title: "EEE", desc: "desc15" },
    { id: 32, img: " ", title: "FFF", desc: "desc15" },
    { id: 33, img: " ", title: "GGG", desc: "desc15" },
    { id: 34, img: " ", title: "HHH", desc: "desc15" },
    { id: 35, img: " ", title: "JJJ", desc: "desc15" },
    { id: 36, img: " ", title: "KKK", desc: "desc15" },
    { id: 37, img: " ", title: "LLL", desc: "desc15" },
    { id: 38, img: " ", title: "MMM", desc: "desc15" },
    { id: 39, img: " ", title: "NNN", desc: "desc15" },
    { id: 40, img: " ", title: "OOO", desc: "desc15" },
    { id: 41, img: " ", title: "PPP", desc: "desc15" },
    { id: 42, img: " ", title: "QQQ", desc: "desc15" },
    { id: 43, img: " ", title: "RRR", desc: "desc15" },
    { id: 44, img: " ", title: "SSS", desc: "desc15" },
    { id: 45, img: " ", title: "TTT", desc: "desc15" },
    { id: 46, img: " ", title: "UUU", desc: "desc15" },
    { id: 47, img: " ", title: "VVV", desc: "desc15" },
    { id: 48, img: " ", title: "WWW", desc: "desc15" },
    { id: 49, img: " ", title: "XXX", desc: "desc15" },
    { id: 50, img: " ", title: "YYY", desc: "desc15" },



  ],
};
